name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps: 
     - name: Checkout
       uses: actions/checkout@v4.1.5
     - name: Cypress.io
       uses: cypress-io/github-action@v6.5.0
       with:
         browser: chrome
         wait-on: "https://www.saucedemo.com/"
